In [49]:
import pandas as pd
import numpy as np
import sklearn

In [50]:
big_data = pd.read_csv(r'..\UFC fighers data\data.csv')
small_data = pd.read_csv(r'..\UFC fighers data\P2_UFC_fighters_data.csv')

In [51]:
big_data.iloc[:,0:20].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6012 entries, 0 to 6011
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   R_fighter              6012 non-null   object
 1   B_fighter              6012 non-null   object
 2   Referee                5980 non-null   object
 3   date                   6012 non-null   object
 4   location               6012 non-null   object
 5   Winner                 6012 non-null   object
 6   title_bout             6012 non-null   bool
 7   weight_class           6012 non-null   object
 8   B_avg_KD               4585 non-null   float64
 9   B_avg_opp_KD           4585 non-null   float64
 10  B_avg_SIG_STR_pct      4585 non-null   float64
 11  B_avg_opp_SIG_STR_pct  4585 non-null   float64
 12  B_avg_TD_pct           4585 non-null   float64
 13  B_avg_opp_TD_pct       4585 non-null   float64
 14  B_avg_SUB_ATT          4585 non-null   float64
 15  B_avg_opp_SUB_ATT      4585 non-null   float64
 16  B_avg_REV              4585 non-null   float64
 17  B_avg_opp_REV          4585 non-null   float64
 18  B_avg_SIG_STR_att      4585 non-null   float64
 19  B_avg_SIG_STR_landed   4585 non-null   float64
dtypes: bool(1), float64(12), object(7)
memory usage: 898.4+ KB

In [52]:
small_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3518 entries, 0 to 3517
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          3518 non-null   int64
 1   fighter_name        3518 non-null   object
 2   Height_cm           3518 non-null   float64
 3   Weight_kg           3518 non-null   int64
 4   Reach_cm            3518 non-null   int64
 5   Stance              3518 non-null   object
 6   SLpM                3518 non-null   float64
 7   Str_Acc%            3518 non-null   float64
 8   Strikes_absorbed/m  3518 non-null   float64
 9   Str_Def%            3518 non-null   float64
 10  TD_Avg              3518 non-null   float64
 11  TD_Def%             3518 non-null   float64
 12  Sub_Avg             3518 non-null   float64
 13  weight_class        3518 non-null   object
 14  TD_Acc              3518 non-null   float64
dtypes: float64(9), int64(3), object(3)
memory usage: 412.4+ KB

In [53]:
# name_with_salary['order'] = name_with_salary['name'].map(
#     {name: index for index, name in enumerate(names_with_age['name'])}
# )
# name_with_salary = name_with_salary.sort_values('order').drop('order', axis=1)

In [ ]:
big_data_names = pd.concat([big_data['R_fighter'], big_data['B_fighter']]).unique()
small_data_names = small_data['fighter_name'].unique()

# Step 2: Create a mapping of names to their order in small_data
name_order = {name: index for index, name in enumerate(small_data_names)}

# Step 3: Add an order column to big_data based on the small_data order
big_data['order'] = big_data['R_fighter'].map(name_order).fillna(-1)  # Use -1 for names not found
big_data['order'] = big_data['order'].where(big_data['order'] != -1, big_data['B_fighter'].map(name_order).fillna(-1))

# Step 4: Sort big_data based on the order column
big_data_sorted = big_data[big_data['order'] != -1].sort_values('order').drop('order', axis=1)

# Display the sorted big_data
print(big_data_sorted)

           R_fighter        B_fighter         Referee        date  \
2255   Felice Herrig    Kailin Curran   John McCarthy  2016-07-23
1823   Felice Herrig     Justine Kish  Keith Peterson  2017-06-25
2857   Felice Herrig    Paige VanZant   Vitor Ribeiro  2015-04-18
310    Felice Herrig  Virna Jandiroba    Marc Goddard  2020-08-15
1608   Felice Herrig    Cortney Casey  BobbyWombacher  2017-12-02
...              ...              ...             ...         ...
5969   Paul Varelans      Cal Worsham   John McCarthy  1995-07-14
5910  Scott Ferrozzo       Jim Mullen   John McCarthy  1997-02-07
5920  Scott Ferrozzo     David Abbott   John McCarthy  1996-09-20
5825   Andre Roberts     Ron Waterman   John McCarthy  1999-07-16
5895      Dan Bobish   Brian Johnston   John McCarthy  1997-07-27

                          location Winner  title_bout      weight_class  \
2255        Chicago, Illinois, USA    Red       False  WomenStrawweight
1823  Oklahoma City, Oklahoma, USA    Red       False  WomenStrawweight
2857       Newark, New Jersey, USA   Blue       False  WomenStrawweight
310         Las Vegas, Nevada, USA   Blue       False  WomenStrawweight
1608        Detroit, Michigan, USA    Red       False  WomenStrawweight
...                            ...    ...         ...               ...
5969          Casper, Wyoming, USA    Red       False        OpenWeight
5910          Dothan, Alabama, USA    Red       False       Heavyweight
5920         Augusta, Georgia, USA    Red       False        OpenWeight
5825       Cedar Rapids, Iowa, USA    Red       False       Heavyweight
5895      Birmingham, Alabama, USA    Red       False       Heavyweight

      B_avg_KD  B_avg_opp_KD  ...  R_win_by_Decision_Unanimous  \
2255    0.0000       0.00000  ...                            0
1823    0.0000       0.00000  ...                            1
2857    0.0000       0.00000  ...                            0
310     0.0000       0.00000  ...                            2
1608    0.0000       0.03125  ...                            2
...        ...           ...  ...                          ...
5969       NaN           NaN  ...                            0
5910       NaN           NaN  ...                            1
5920    0.0625       0.00000  ...                            0
5825    0.0000       0.00000  ...                            0
5895    0.0000       0.00000  ...                            0

      R_win_by_KO/TKO  R_win_by_Submission  R_win_by_TKO_Doctor_Stoppage  \
2255                0                    1                             0
1823                0                    2                             0
2857                0                    1                             0
310                 0                    2                             0
1608                0                    2                             0
...               ...                  ...                           ...
5969                0                    0                             0
5910                0                    0                             0
5920                0                    0                             0
5825                0                    0                             0
5895                0                    0                             0

      R_Stance  R_Height_cms  R_Reach_cms  R_Weight_lbs  B_age  R_age
2255  Orthodox        162.56        165.1         115.0   25.0   31.0
1823  Orthodox        162.56        165.1         115.0   29.0   32.0
2857  Orthodox        162.56        165.1         115.0   21.0   30.0
310   Orthodox        162.56        165.1         115.0   32.0   35.0
1608  Orthodox        162.56        165.1         115.0   30.0   33.0
...        ...           ...          ...           ...    ...    ...
5969  Orthodox        203.20          NaN         300.0    NaN    NaN
5910  Orthodox        180.34          NaN         323.0    NaN   31.0
5920  Orthodox        180.34          NaN         323.0    NaN   31.0
5825  Orthodox        187.96          NaN         345.0   33.0   34.0
5895  Southpaw        187.96          NaN         345.0    NaN   27.0

[6011 rows x 144 columns]

In [ ]:
columns_to_drop = big_data_sorted.filter(like='B').columns

# Step 2: Drop those columns
big_data_sorted= big_data_sorted.drop(columns=columns_to_drop)

In [ ]:
big_data_sorted.drop(columns=['Referee'], inplace=True)

In [60]:
big_data_sorted = big_data_sorted.loc[:, ~big_data_sorted.columns.str.contains('opp')]
big_data_sorted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6011 entries, 2255 to 5895
Data columns (total 46 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   R_fighter                     6011 non-null   object
 1   date                          6011 non-null   object
 2   location                      6011 non-null   object
 3   Winner                        6011 non-null   object
 4   title_bout                    6011 non-null   bool
 5   weight_class                  6011 non-null   object
 6   R_avg_KD                      5300 non-null   float64
 7   R_avg_SIG_STR_pct             5300 non-null   float64
 8   R_avg_TD_pct                  5300 non-null   float64
 9   R_avg_REV                     5300 non-null   float64
 10  R_avg_SIG_STR_att             5300 non-null   float64
 11  R_avg_SIG_STR_landed          5300 non-null   float64
 12  R_avg_TOTAL_STR_att           5300 non-null   float64
 13  R_avg_TOTAL_STR_landed        5300 non-null   float64
 14  R_avg_TD_att                  5300 non-null   float64
 15  R_avg_TD_landed               5300 non-null   float64
 16  R_avg_HEAD_att                5300 non-null   float64
 17  R_avg_HEAD_landed             5300 non-null   float64
 18  R_avg_LEG_att                 5300 non-null   float64
 19  R_avg_LEG_landed              5300 non-null   float64
 20  R_avg_DISTANCE_att            5300 non-null   float64
 21  R_avg_DISTANCE_landed         5300 non-null   float64
 22  R_avg_CLINCH_att              5300 non-null   float64
 23  R_avg_CLINCH_landed           5300 non-null   float64
 24  R_avg_GROUND_att              5300 non-null   float64
 25  R_avg_GROUND_landed           5300 non-null   float64
 26  R_avg_CTRL_time(seconds)      5300 non-null   float64
 27  R_total_time_fought(seconds)  5300 non-null   float64
 28  R_total_rounds_fought         6011 non-null   int64
 29  R_total_title_bouts           6011 non-null   int64
 30  R_current_win_streak          6011 non-null   int64
 31  R_current_lose_streak         6011 non-null   int64
 32  R_longest_win_streak          6011 non-null   int64
 33  R_wins                        6011 non-null   int64
 34  R_losses                      6011 non-null   int64
 35  R_draw                        6011 non-null   int64
 36  R_win_by_Decision_Majority    6011 non-null   int64
 37  R_win_by_Decision_Split       6011 non-null   int64
 38  R_win_by_Decision_Unanimous   6011 non-null   int64
 39  R_win_by_KO/TKO               6011 non-null   int64
 40  R_win_by_Submission           6011 non-null   int64
 41  R_Stance                      5983 non-null   object
 42  R_Height_cms                  6008 non-null   float64
 43  R_Reach_cms                   5606 non-null   float64
 44  R_Weight_lbs                  6010 non-null   float64
 45  R_age                         5949 non-null   float64
dtypes: bool(1), float64(26), int64(13), object(6)
memory usage: 2.1+ MB

In [62]:
big_data_sorted.isna().sum()

R_fighter                         0
date                              0
location                          0
Winner                            0
title_bout                        0
weight_class                      0
R_avg_KD                        711
R_avg_SIG_STR_pct               711
R_avg_TD_pct                    711
R_avg_REV                       711
R_avg_SIG_STR_att               711
R_avg_SIG_STR_landed            711
R_avg_TOTAL_STR_att             711
R_avg_TOTAL_STR_landed          711
R_avg_TD_att                    711
R_avg_TD_landed                 711
R_avg_HEAD_att                  711
R_avg_HEAD_landed               711
R_avg_LEG_att                   711
R_avg_LEG_landed                711
R_avg_DISTANCE_att              711
R_avg_DISTANCE_landed           711
R_avg_CLINCH_att                711
R_avg_CLINCH_landed             711
R_avg_GROUND_att                711
R_avg_GROUND_landed             711
R_avg_CTRL_time(seconds)        711
R_total_time_fought(seconds)    711
R_total_rounds_fought             0
R_total_title_bouts               0
R_current_win_streak              0
R_current_lose_streak             0
R_longest_win_streak              0
R_wins                            0
R_losses                          0
R_draw                            0
R_win_by_Decision_Majority        0
R_win_by_Decision_Split           0
R_win_by_Decision_Unanimous       0
R_win_by_KO/TKO                   0
R_win_by_Submission               0
R_Stance                         28
R_Height_cms                      3
R_Reach_cms                     405
R_Weight_lbs                      1
R_age                            62
dtype: int64

In [96]:
# Select numerical columns from the DataFrame
numerical_columns = big_data_sorted.select_dtypes(include=['float64', 'int64']).columns

# Step 1: Group by 'R_fighter' and calculate the mean for all numerical columns
fighter_mean_values = big_data_sorted.groupby('R_fighter')[numerical_columns].transform('mean')

# Step 2: Fill missing values in all numerical columns with the corresponding fighter's mean value
big_data_sorted[numerical_columns] = big_data_sorted[numerical_columns].fillna(fighter_mean_values)

# Check the result
big_data_sorted.isna().sum()

R_fighter                         0
date                              0
location                          0
Winner                            0
title_bout                        0
weight_class                      0
R_avg_KD                        204
R_avg_SIG_STR_pct               204
R_avg_TD_pct                    204
R_avg_REV                       204
R_avg_SIG_STR_att               204
R_avg_SIG_STR_landed            204
R_avg_TOTAL_STR_att             204
R_avg_TOTAL_STR_landed          204
R_avg_TD_att                    204
R_avg_TD_landed                 204
R_avg_HEAD_att                  204
R_avg_HEAD_landed               204
R_avg_LEG_att                   204
R_avg_LEG_landed                204
R_avg_DISTANCE_att              204
R_avg_DISTANCE_landed           204
R_avg_CLINCH_att                204
R_avg_CLINCH_landed             204
R_avg_GROUND_att                204
R_avg_GROUND_landed             204
R_avg_CTRL_time(seconds)        204
R_total_time_fought(seconds)    204
R_total_rounds_fought             0
R_total_title_bouts               0
R_current_win_streak              0
R_current_lose_streak             0
R_longest_win_streak              0
R_wins                            0
R_losses                          0
R_draw                            0
R_win_by_Decision_Majority        0
R_win_by_Decision_Split           0
R_win_by_Decision_Unanimous       0
R_win_by_KO/TKO                   0
R_win_by_Submission               0
R_Stance                         28
R_Height_cms                      3
R_Reach_cms                     405
R_Weight_lbs                      1
R_age                            62
dtype: int64

In [105]:
# Drop duplicate rows based on the 'R_fighter' column, keeping only the first occurrence
big_data_filtered = big_data_sorted.drop_duplicates(subset='R_fighter', keep='first')
big_data_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1513 entries, 2255 to 5895
Data columns (total 46 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   R_fighter                     1513 non-null   object
 1   date                          1513 non-null   object
 2   location                      1513 non-null   object
 3   Winner                        1513 non-null   object
 4   title_bout                    1513 non-null   bool
 5   weight_class                  1513 non-null   object
 6   R_avg_KD                      1309 non-null   float64
 7   R_avg_SIG_STR_pct             1309 non-null   float64
 8   R_avg_TD_pct                  1309 non-null   float64
 9   R_avg_REV                     1309 non-null   float64
 10  R_avg_SIG_STR_att             1309 non-null   float64
 11  R_avg_SIG_STR_landed          1309 non-null   float64
 12  R_avg_TOTAL_STR_att           1309 non-null   float64
 13  R_avg_TOTAL_STR_landed        1309 non-null   float64
 14  R_avg_TD_att                  1309 non-null   float64
 15  R_avg_TD_landed               1309 non-null   float64
 16  R_avg_HEAD_att                1309 non-null   float64
 17  R_avg_HEAD_landed             1309 non-null   float64
 18  R_avg_LEG_att                 1309 non-null   float64
 19  R_avg_LEG_landed              1309 non-null   float64
 20  R_avg_DISTANCE_att            1309 non-null   float64
 21  R_avg_DISTANCE_landed         1309 non-null   float64
 22  R_avg_CLINCH_att              1309 non-null   float64
 23  R_avg_CLINCH_landed           1309 non-null   float64
 24  R_avg_GROUND_att              1309 non-null   float64
 25  R_avg_GROUND_landed           1309 non-null   float64
 26  R_avg_CTRL_time(seconds)      1309 non-null   float64
 27  R_total_time_fought(seconds)  1309 non-null   float64
 28  R_total_rounds_fought         1513 non-null   int64
 29  R_total_title_bouts           1513 non-null   int64
 30  R_current_win_streak          1513 non-null   int64
 31  R_current_lose_streak         1513 non-null   int64
 32  R_longest_win_streak          1513 non-null   int64
 33  R_wins                        1513 non-null   int64
 34  R_losses                      1513 non-null   int64
 35  R_draw                        1513 non-null   int64
 36  R_win_by_Decision_Majority    1513 non-null   int64
 37  R_win_by_Decision_Split       1513 non-null   int64
 38  R_win_by_Decision_Unanimous   1513 non-null   int64
 39  R_win_by_KO/TKO               1513 non-null   int64
 40  R_win_by_Submission           1513 non-null   int64
 41  R_Stance                      1489 non-null   object
 42  R_Height_cms                  1510 non-null   float64
 43  R_Reach_cms                   1273 non-null   float64
 44  R_Weight_lbs                  1512 non-null   float64
 45  R_age                         1473 non-null   float64
dtypes: bool(1), float64(26), int64(13), object(6)
memory usage: 545.2+ KB

In [108]:
big_data_filtered.head()

,R_fighter,date,location,Winner,title_bout,weight_class,R_avg_KD,R_avg_SIG_STR_pct,R_avg_TD_pct,R_avg_REV,...,R_win_by_Decision_Majority,R_win_by_Decision_Split,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,R_age
0,Felice Herrig,2016-07-23,"Chicago, Illinois, USA",Red,False,WomenStrawweight,0.0,0.580000,0.500000,1.50,...,0,0,0,0,1,Orthodox,162.56,165.10,115.0,31.0
1,Tecia Torres,2015-12-12,"Las Vegas, Nevada, USA",Red,False,WomenStrawweight,0.5,0.440000,0.580000,0.00,...,0,0,2,0,0,Orthodox,154.94,152.40,115.0,26.0
2,Loma Lookboonmee,2020-02-22,"Auckland, New Zealand",Blue,False,WomenStrawweight,0.0,0.650000,0.160000,0.00,...,0,1,0,0,0,Orthodox,154.94,154.94,115.0,24.0
3,Amanda Lemos,2020-08-22,"Las Vegas, Nevada, USA",Red,False,WomenStrawweight,0.0,0.650000,1.000000,0.00,...,0,0,0,0,1,Southpaw,162.56,165.10,115.0,33.0
4,Carla Esparza,2018-09-08,"Dallas, Texas, USA",Blue,False,WomenStrawweight,0.0,0.388125,0.416563,0.25,...,0,0,3,0,1,Orthodox,154.94,160.02,115.0,30.0

In [107]:
# Reset the index and drop the old index
big_data_filtered = big_data_filtered.reset_index(drop=True)

In [113]:
big_data_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1513 entries, 0 to 1512
Data columns (total 46 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   R_fighter                     1513 non-null   object
 1   date                          1513 non-null   object
 2   location                      1513 non-null   object
 3   Winner                        1513 non-null   object
 4   title_bout                    1513 non-null   bool
 5   weight_class                  1513 non-null   object
 6   R_avg_KD                      1309 non-null   float64
 7   R_avg_SIG_STR_pct             1309 non-null   float64
 8   R_avg_TD_pct                  1309 non-null   float64
 9   R_avg_REV                     1309 non-null   float64
 10  R_avg_SIG_STR_att             1309 non-null   float64
 11  R_avg_SIG_STR_landed          1309 non-null   float64
 12  R_avg_TOTAL_STR_att           1309 non-null   float64
 13  R_avg_TOTAL_STR_landed        1309 non-null   float64
 14  R_avg_TD_att                  1309 non-null   float64
 15  R_avg_TD_landed               1309 non-null   float64
 16  R_avg_HEAD_att                1309 non-null   float64
 17  R_avg_HEAD_landed             1309 non-null   float64
 18  R_avg_LEG_att                 1309 non-null   float64
 19  R_avg_LEG_landed              1309 non-null   float64
 20  R_avg_DISTANCE_att            1309 non-null   float64
 21  R_avg_DISTANCE_landed         1309 non-null   float64
 22  R_avg_CLINCH_att              1309 non-null   float64
 23  R_avg_CLINCH_landed           1309 non-null   float64
 24  R_avg_GROUND_att              1309 non-null   float64
 25  R_avg_GROUND_landed           1309 non-null   float64
 26  R_avg_CTRL_time(seconds)      1309 non-null   float64
 27  R_total_time_fought(seconds)  1309 non-null   float64
 28  R_total_rounds_fought         1513 non-null   int64
 29  R_total_title_bouts           1513 non-null   int64
 30  R_current_win_streak          1513 non-null   int64
 31  R_current_lose_streak         1513 non-null   int64
 32  R_longest_win_streak          1513 non-null   int64
 33  R_wins                        1513 non-null   int64
 34  R_losses                      1513 non-null   int64
 35  R_draw                        1513 non-null   int64
 36  R_win_by_Decision_Majority    1513 non-null   int64
 37  R_win_by_Decision_Split       1513 non-null   int64
 38  R_win_by_Decision_Unanimous   1513 non-null   int64
 39  R_win_by_KO/TKO               1513 non-null   int64
 40  R_win_by_Submission           1513 non-null   int64
 41  R_Stance                      1489 non-null   object
 42  R_Height_cms                  1510 non-null   float64
 43  R_Reach_cms                   1273 non-null   float64
 44  R_Weight_lbs                  1512 non-null   float64
 45  R_age                         1473 non-null   float64
dtypes: bool(1), float64(26), int64(13), object(6)
memory usage: 533.5+ KB

In [120]:
# big_data_filtered.drop(columns=['R_Stance'],inplace=True)

In [123]:
# Merge on 'fighter_name' from small_data and 'R_fighter' from big_data_filtered
merged_data = pd.merge(small_data, big_data_filtered, left_on='fighter_name', right_on='R_fighter', how='inner')

# Optionally, drop the 'R_fighter' column if it's redundant after merge
merged_data = merged_data.drop(columns=['R_fighter'])

# Check the result
merged_data.head()

,Unnamed: 0,fighter_name,Height_cm,Weight_kg,Reach_cm,Stance,SLpM,Str_Acc%,Strikes_absorbed/m,Str_Def%,...,R_wins,R_losses,R_draw,R_win_by_Decision_Majority,R_win_by_Decision_Split,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_Height_cms,R_age
0,0,Felice Herrig,162.56,52,65,Orthodox,3.63,36.0,4.84,49.0,...,1,1,0,0,0,0,0,1,162.56,31.0
1,1,Tecia Torres,154.94,52,60,Southpaw,4.30,47.0,3.37,62.0,...,2,0,0,0,0,2,0,0,154.94,26.0
2,2,Loma Lookboonmee,154.94,52,61,Southpaw,5.16,55.0,3.09,59.0,...,1,0,0,0,1,0,0,0,154.94,24.0
3,3,Amanda Lemos,162.56,52,65,Southpaw,6.21,64.0,5.39,45.0,...,1,1,0,0,0,0,0,1,162.56,33.0
4,4,Carla Esparza,154.94,52,63,Orthodox,2.29,42.0,2.85,53.0,...,4,3,0,0,0,3,0,1,154.94,30.0

In [121]:
big_data_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1513 entries, 0 to 1512
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   R_fighter                     1513 non-null   object
 1   date                          1513 non-null   object
 2   location                      1513 non-null   object
 3   Winner                        1513 non-null   object
 4   title_bout                    1513 non-null   bool
 5   weight_class                  1513 non-null   object
 6   R_avg_KD                      1309 non-null   float64
 7   R_avg_SIG_STR_pct             1309 non-null   float64
 8   R_avg_TD_pct                  1309 non-null   float64
 9   R_avg_REV                     1309 non-null   float64
 10  R_avg_SIG_STR_att             1309 non-null   float64
 11  R_avg_SIG_STR_landed          1309 non-null   float64
 12  R_avg_TOTAL_STR_att           1309 non-null   float64
 13  R_avg_TOTAL_STR_landed        1309 non-null   float64
 14  R_avg_TD_att                  1309 non-null   float64
 15  R_avg_TD_landed               1309 non-null   float64
 16  R_avg_HEAD_att                1309 non-null   float64
 17  R_avg_HEAD_landed             1309 non-null   float64
 18  R_avg_LEG_att                 1309 non-null   float64
 19  R_avg_LEG_landed              1309 non-null   float64
 20  R_avg_DISTANCE_att            1309 non-null   float64
 21  R_avg_DISTANCE_landed         1309 non-null   float64
 22  R_avg_CLINCH_att              1309 non-null   float64
 23  R_avg_CLINCH_landed           1309 non-null   float64
 24  R_avg_GROUND_att              1309 non-null   float64
 25  R_avg_GROUND_landed           1309 non-null   float64
 26  R_avg_CTRL_time(seconds)      1309 non-null   float64
 27  R_total_time_fought(seconds)  1309 non-null   float64
 28  R_total_rounds_fought         1513 non-null   int64
 29  R_total_title_bouts           1513 non-null   int64
 30  R_current_win_streak          1513 non-null   int64
 31  R_current_lose_streak         1513 non-null   int64
 32  R_longest_win_streak          1513 non-null   int64
 33  R_wins                        1513 non-null   int64
 34  R_losses                      1513 non-null   int64
 35  R_draw                        1513 non-null   int64
 36  R_win_by_Decision_Majority    1513 non-null   int64
 37  R_win_by_Decision_Split       1513 non-null   int64
 38  R_win_by_Decision_Unanimous   1513 non-null   int64
 39  R_win_by_KO/TKO               1513 non-null   int64
 40  R_win_by_Submission           1513 non-null   int64
 41  R_Height_cms                  1510 non-null   float64
 42  R_age                         1473 non-null   float64
dtypes: bool(1), float64(24), int64(13), object(5)
memory usage: 498.1+ KB

In [112]:
small_data.iloc[100:200]

,Unnamed: 0,fighter_name,Height_cm,Weight_kg,Reach_cm,Stance,SLpM,Str_Acc%,Strikes_absorbed/m,Str_Def%,TD_Avg,TD_Def%,Sub_Avg,weight_class,TD_Acc
100,100,Lara Procopio,162.56,56,67,Orthodox,6.70,57.00,6.93,47.00,3.50,60.76,0.5,Bantam Weight,50.00
101,101,Lucie Pudilova,172.72,56,67,Southpaw,4.15,36.00,4.09,52.00,0.16,61.00,0.6,Bantam Weight,12.00
102,102,Chris Cariaso,160.02,56,64,Southpaw,3.35,43.00,2.23,61.00,1.11,57.00,0.8,Bantam Weight,39.00
103,103,Matt Schnell,172.72,56,70,Southpaw,4.20,36.00,4.02,62.00,0.48,53.00,1.2,Bantam Weight,33.00
104,104,Lacey Schuckman,160.02,56,66,Orthodox,0.00,42.12,0.00,55.91,0.00,60.76,0.0,Bantam Weight,44.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,Marco Beltran,172.72,56,69,Southpaw,2.07,37.00,1.93,63.00,0.70,46.00,0.2,Bantam Weight,50.00
196,196,Joseph Benavidez,162.56,56,65,Southpaw,3.52,34.00,2.67,61.00,1.41,62.00,0.6,Bantam Weight,30.00
197,197,DeAnna Bennett,162.56,56,68,Orthodox,3.13,58.00,3.27,58.00,0.00,60.76,1.0,Bantam Weight,44.09
198,198,Nick Urso,167.64,56,66,Southpaw,3.61,45.00,5.06,36.00,0.00,60.76,0.0,Bantam Weight,44.09
199,199,Yasuhiro Urushitani,165.10,56,66,Southpaw,3.47,39.00,4.71,65.00,0.00,80.00,0.0,Bantam Weight,44.09

In [111]:
big_data_filtered.iloc[100:200]

,R_fighter,date,location,Winner,title_bout,weight_class,R_avg_KD,R_avg_SIG_STR_pct,R_avg_TD_pct,R_avg_REV,...,R_win_by_Decision_Majority,R_win_by_Decision_Split,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,R_age
100,JJ Aldrich,2017-06-10,"Auckland, New Zealand",Red,False,WomenStrawweight,0.000000,0.380000,0.0000,0.0,...,0,0,0,0,0,Southpaw,165.10,170.18,125.0,24.0
101,Gina Mazany,2019-03-02,"Las Vegas, Nevada, USA",Blue,False,WomenBantamweight,0.000000,0.355000,0.6775,0.0,...,0,0,1,0,0,Southpaw,167.64,172.72,125.0,30.0
102,Karine Gevorgyan,2017-12-01,"Las Vegas, Nevada, USA",Blue,False,WomenFlyweight,NaN,NaN,NaN,NaN,...,0,0,0,0,0,NaN,162.56,160.02,125.0,28.0
103,Darrell Montague,2015-07-12,"Las Vegas, Nevada, USA",Blue,False,Flyweight,0.000000,0.255000,0.2500,0.0,...,0,0,0,0,0,Southpaw,167.64,170.18,125.0,27.0
104,Ryan Benoit,2016-07-30,"Atlanta, Georgia, USA",Red,False,Flyweight,0.250000,0.227500,0.2500,0.5,...,0,0,0,1,0,Orthodox,165.10,172.72,125.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Aiemann Zahabi,2019-05-04,"Ottawa, Ontario, Canada",Blue,False,Bantamweight,0.500000,0.410000,0.0000,0.5,...,0,0,1,0,0,Orthodox,172.72,172.72,135.0,31.0
196,Francisco Rivera,2015-09-05,"Las Vegas, Nevada, USA",Blue,False,Bantamweight,0.617188,0.441406,0.1250,0.0,...,0,0,1,3,0,Orthodox,172.72,177.80,135.0,33.0
197,Ian Entwistle,2016-04-10,"Zagreb, Croatia",Blue,False,Bantamweight,0.000000,0.055000,0.0000,0.0,...,0,0,0,0,1,Orthodox,165.10,NaN,135.0,29.0
198,Cole Escovedo,2011-05-28,"Las Vegas, Nevada, USA",Blue,False,Bantamweight,NaN,NaN,NaN,NaN,...,0,0,0,0,0,Orthodox,170.18,182.88,135.0,29.0
199,Lina Lansberg,2018-05-27,"Liverpool, England, United Kingdom",Red,False,WomenBantamweight,0.000000,0.607500,0.0350,0.0,...,0,0,1,0,0,Orthodox,170.18,165.10,135.0,36.0

In [ ]:
# merged_data.to_csv('merged_data.csv')

In [125]:
merged_data.isna().sum()

Unnamed: 0                        0
fighter_name                      0
Height_cm                         0
Weight_kg                         0
Reach_cm                          0
Stance                            0
SLpM                              0
Str_Acc%                          0
Strikes_absorbed/m                0
Str_Def%                          0
TD_Avg                            0
TD_Def%                           0
Sub_Avg                           0
weight_class_x                    0
TD_Acc                            0
date                              0
location                          0
Winner                            0
title_bout                        0
weight_class_y                    0
R_avg_KD                        203
R_avg_SIG_STR_pct               203
R_avg_TD_pct                    203
R_avg_REV                       203
R_avg_SIG_STR_att               203
R_avg_SIG_STR_landed            203
R_avg_TOTAL_STR_att             203
R_avg_TOTAL_STR_landed          203
R_avg_TD_att                    203
R_avg_TD_landed                 203
R_avg_HEAD_att                  203
R_avg_HEAD_landed               203
R_avg_LEG_att                   203
R_avg_LEG_landed                203
R_avg_DISTANCE_att              203
R_avg_DISTANCE_landed           203
R_avg_CLINCH_att                203
R_avg_CLINCH_landed             203
R_avg_GROUND_att                203
R_avg_GROUND_landed             203
R_avg_CTRL_time(seconds)        203
R_total_time_fought(seconds)    203
R_total_rounds_fought             0
R_total_title_bouts               0
R_current_win_streak              0
R_current_lose_streak             0
R_longest_win_streak              0
R_wins                            0
R_losses                          0
R_draw                            0
R_win_by_Decision_Majority        0
R_win_by_Decision_Split           0
R_win_by_Decision_Unanimous       0
R_win_by_KO/TKO                   0
R_win_by_Submission               0
R_Height_cms                      2
R_age                            39
dtype: int64